name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./volumen:/volumen
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./volumen:/volumen
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./volumen:/volumen
  client4:
    container_name: client4
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./volumen:/volumen
  client5:
    container_name: client5
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./volumen:/volumen
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./volumen:/volumen
version: '3.9'
